name: sipp_mobile
description: "Sistem Informasi Penunjang Penelitian"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0+4

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1
  http: ^1.2.0
  encrypt: ^5.0.1
  flutter_secure_storage: ^6.0.0
  get_it: ^7.6.7
  intl: ^0.18.0
  image_picker: ^1.0.4
  provider: ^6.0.2
  flutter_map: ^6.1.0
  go_router: ^13.2.1
  image: ^3.0.1
  latlong2: ^0.9.1
  shimmer: ^3.0.0
  flutter_easyloading: ^3.0.5
  flutter_image_compress: ^2.3.0
  firebase_core: ^2.27.0
  firebase_analytics: ^10.0.7
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/general/
    - assets/images/general/2x/
    - assets/images/general/3x/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
