// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmt2dbGHe_sgySReiaYs8gVhqnCEeiBWg',
    appId: '1:804147215638:web:73cb6fa7f311114df0a437',
    messagingSenderId: '804147215638',
    projectId: 'sipp-mobile-316d1',
    authDomain: 'sipp-mobile-316d1.firebaseapp.com',
    storageBucket: 'sipp-mobile-316d1.appspot.com',
    measurementId: 'G-HZQ8JPHYER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgcM-l-kxrwZKB6De8R3eexlLYrPMvgmE',
    appId: '1:804147215638:android:4257a2820a12dd87f0a437',
    messagingSenderId: '804147215638',
    projectId: 'sipp-mobile-316d1',
    storageBucket: 'sipp-mobile-316d1.appspot.com',
  );
}
